version: '3.0'
services:

# Application Containers ------------------------------------------------------

  django:
    restart: always
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    environment:
      - DEBUG=False
      - DJANGO_LOG_LEVEL=ERROR
      - SECRET_KEY
      - ALLOWED_HOSTS
    ports:
      - "${PORT_BACKEND}:8000"

  sass:
    build:
      context: docker/sass
    volumes:
       - ./backend/radioco/main/static/main/:/workdir
    working_dir: /workdir
